version: 1.0.0.{build}
image: Visual Studio 2017 Preview

# prevent the double build when a branch has an active PR
skip_branch_with_pr: true

environment:
  matrix:

#    - target_framework: netcoreapp2.1
#      is_32bit: False

#    - target_framework: netcoreapp2.1
#      is_32bit: True

    - target_framework: netcoreapp2.0
      is_32bit: False

    - target_framework: net471
      is_32bit: False

    - target_framework: net471
      is_32bit: True

    - target_framework: net462
      is_32bit: False

    - target_framework: net462
      is_32bit: True
    
    #- target_framework: netcoreapp2.0 # As far as I understand, 32 bit test execution is not supported by "dotnet xunit"
    #  is_32bit: True
    #- target_framework: mono
    #  is_32bit: False
    #- target_framework: mono
    #  is_32bit: True
    #- target_framework: net47
    #  is_32bit: False
    #- target_framework: net47
    #  is_32bit: True

install:
  - ps: |
        if ($env:target_framework -eq "mono") { 
          if ($env:is_32bit -eq "True") { 
            cinst mono --x86
          } else { 
            cinst mono
          }
        }

before_build:
  - git submodule -q update --init
  - cmd: dotnet --info
  
build_script:
- cmd: build\build.cmd

after_build:
  - cmd: appveyor PushArtifact "artifacts\Orleans.Clustering.Cassandra.%APPVEYOR_BUILD_VERSION%.nupkg"

#test_script:
#- ps: .\run-tests.ps1 $env:target_framework $env:is_32bit

#after_test:
#  - cmd: appveyor PushArtifact "artifacts\Orleans.Clustering.Cassandra.%APPVEYOR_BUILD_VERSION%.nupkg"

deploy:
    # MyGet Deployment for builds & releases
  - provider: NuGet
    server: https://www.myget.org/F/orleans-cassandra/api/v2/package
    symbol_server: https://www.myget.org/F/orleans-cassandra/symbols/api/v2/package
    api_key:
      secure: oS9xcmuI1FbfAD8D2GGqI3XNFep6/ZcM7KCA9coG27SgnfnYyg8lx4VCfCfQ1Omb
    artifact: /.*\.nupkg/
    on:
      branch: master